#!/bin/sh

#---------------------------------------------------------
#	Add Doc path to $PATH (depends on OS used)
#---------------------------------------------------------
TANGO_HOME=/segfs/tango
MY_OS=`uname`
export MY_OS

if [ $MY_OS = "SunOS" ]
then
	OS_DIR=solaris8/doxygen-1.2.14/
else
	if [ $MY_OS == "Linux" ]
	then
		OS_DIR=suse72
	fi
fi


#CPP_DOC=NOT_INSTALLED
CPP_DOC=$TANGO_HOME/doc/www/doxygen/$OS_DIR/bin
echo $CPP_DOC
#---------------------------------------------------------
#	Set the template path
#---------------------------------------------------------
TEMPLATES=/segfs/tango/tools/pogo/templates
export TEMPLATES

#---------------------------------------------------------
#	Set the Home Source Path
#---------------------------------------------------------
SRC_PATH=../test/cpp/PowerSupply
#SRC_PATH=../test/cpp/DataSocket/src
#SRC_PATH=../test/cpp/AbstractClasses
#SRC_PATH=../test/cpp/Hazemeyer
#SRC_PATH=../test/java/Test
#SRC_PATH=../test/cpp/sy-tunemon
#SRC_PATH=../test/cpp/PowerSupply/Impl_2_test
#SRC_PATH=/segfs/tango/cppserver/dbserver/tmp
#SRC_PATH=../test/cpp/test
SRC_PATH=/segfs/tango/tools/pogo/test/cpp/aa


#SRC_PATH=../test/cpp

#SRC_PATH=/segfs/tango/cppserver
#SRC_PATH=/segfs/tango/cppserver/admin/starter
#SRC_PATH=/segfs/tango/cppserver/vacuum/gauges

export SRC_PATH

#---------------------------------------------------------
#	Set the Class Path for Tango and pogo usage
#---------------------------------------------------------
POGOCLASS=/segfs/tango/tools/bin;              export POGOCLASS
#POGOCLASS=/segfs/tango/bin/java/Pogo.jar;     export POGOCLASS
TANGOCLASS=/segfs/tango/lib/java/TangORB.jar;  export TANGOCLASS
CLASSPATH=$POGOCLASS:$TANGOCLASS;              export CLASSPATH

export CLASSPATH
echo "CLASSPATH=$CLASSPATH"


#---------------------------------------------------------
#	Start the Pogo process
#---------------------------------------------------------
echo ""
echo "Starting Pogo Appli under $MY_OS.  Be patient...."
echo "Do not forget, it is a java program...."
echo ""
#PARAM="-doc ../test/cpp/RS/RhodesSchwarz.h 	\
#			$TANGO_HOME/tools/pogo/test/java/PowerSupply/PowerSupply.java"

java	-DTEMPL_HOME=$TEMPLATES		\
		-DCPP_DOC_PATH=$CPP_DOC		\
		-DHOME_GENE=$SRC_PATH		\
		-DEDITOR=$POGO_EDITOR		\
		-DPOGO_FILE=$IN_FILE		\
		-DPOGO_TEST=true			\
		-DSUPER_HOME=/segfs/tango/tools/pogo/test/cpp/AbstractClasses	\
		pogo.appli.PogoAppli $PARAM $*


#		-DSUPER_HOME=/segfs/tango/templates/AbstractClasses	\

