
/*
 * generated by Xtext
 */
package fr.esrf.tango.pogo;

import org.eclipse.xtext.Constants;
import org.eclipse.xtext.service.DefaultRuntimeModule;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Manual modifications go to {fr.esrf.tango.pogo.PogoDslRuntimeModule}
 */
public abstract class AbstractPogoDslRuntimeModule extends DefaultRuntimeModule {
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(String.class).annotatedWith(Names.named(Constants.LANGUAGE_NAME)).toInstance(
			"fr.esrf.tango.pogo.PogoDsl");
	}
	
	
	// contributed by org.eclipse.xtext.generator.grammarAccess.GrammarAccessFragment
	public Class<? extends org.eclipse.xtext.IGrammarAccess> bindIGrammarAccess() {
		return fr.esrf.tango.pogo.services.PogoDslGrammarAccess.class;
	}

	// contributed by org.eclipse.xtext.generator.parseTreeConstructor.ParseTreeConstructorFragment
	public Class<? extends org.eclipse.xtext.parsetree.reconstr.IParseTreeConstructor> bindIParseTreeConstructor() {
		return fr.esrf.tango.pogo.parseTreeConstruction.PogoDslParsetreeConstructor.class;
	}

	// contributed by de.itemis.xtext.antlr.XtextAntlrGeneratorFragment
	public Class<? extends org.eclipse.xtext.parser.antlr.IAntlrParser> bindIAntlrParser() {
		return fr.esrf.tango.pogo.parser.antlr.PogoDslParser.class;
	}

	// contributed by de.itemis.xtext.antlr.XtextAntlrGeneratorFragment
	public Class<? extends org.eclipse.xtext.parser.ITokenToStringConverter> bindITokenToStringConverter() {
		return org.eclipse.xtext.parser.antlr.AntlrTokenToStringConverter.class;
	}

	// contributed by de.itemis.xtext.antlr.XtextAntlrGeneratorFragment
	public Class<? extends org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider> bindIAntlrTokenFileProvider() {
		return fr.esrf.tango.pogo.parser.antlr.PogoDslAntlrTokenFileProvider.class;
	}

	// contributed by de.itemis.xtext.antlr.XtextAntlrGeneratorFragment
	public Class<? extends org.eclipse.xtext.parser.antlr.Lexer> bindLexer() {
		return fr.esrf.tango.pogo.parser.antlr.internal.InternalPogoDslLexer.class;
	}

	// contributed by de.itemis.xtext.antlr.XtextAntlrGeneratorFragment
	public Class<? extends org.eclipse.xtext.parser.antlr.ITokenDefProvider> bindITokenDefProvider() {
		return org.eclipse.xtext.parser.antlr.AntlrTokenDefProvider.class;
	}

	// contributed by org.eclipse.xtext.generator.validation.JavaValidatorFragment
	@org.eclipse.xtext.service.SingletonBinding(eager=true)	public Class<? extends fr.esrf.tango.pogo.validation.PogoDslJavaValidator> bindPogoDslJavaValidator() {
		return fr.esrf.tango.pogo.validation.PogoDslJavaValidator.class;
	}

	// contributed by org.eclipse.xtext.generator.validation.CheckFragment
	public Class<? extends org.eclipse.xtend.expression.ExecutionContext> bindExecutionContext() {
		return org.eclipse.xtext.xtend.InjectableExecutionContext.class;
	}

	// contributed by org.eclipse.xtext.generator.validation.CheckFragment
	public Class<? extends org.eclipse.xtend.expression.ResourceManager> bindResourceManager() {
		return org.eclipse.xtext.xtend.InjectableResourceManager.class;
	}

	// contributed by org.eclipse.xtext.generator.validation.CheckFragment
	public java.lang.ClassLoader bindClassLoaderToInstance() {
		return AbstractPogoDslRuntimeModule.class.getClassLoader();
	}

	// contributed by org.eclipse.xtext.generator.validation.CheckFragment
	@org.eclipse.xtext.service.SingletonBinding(eager=true)	public Class<? extends fr.esrf.tango.pogo.validation.PogoDslCheckValidator> bindPogoDslCheckValidator() {
		return fr.esrf.tango.pogo.validation.PogoDslCheckValidator.class;
	}

	// contributed by org.eclipse.xtext.generator.scoping.JavaScopingFragment
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return fr.esrf.tango.pogo.scoping.PogoDslScopeProvider.class;
	}

	// contributed by org.eclipse.xtext.generator.formatting.FormatterFragment
	public Class<? extends org.eclipse.xtext.formatting.IFormatter> bindIFormatter() {
		return fr.esrf.tango.pogo.formatting.PogoDslFormatter.class;
	}

}
