
package org.tango.pogo.pogo_gui;

/**
 *	HTML code to display Release Notes for this package.
 *	It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote
{
	public final String	str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<HTML>\n" + 
		"<HEAD>\n" + 
		"<Title> Release Note </Title>\n" + 
		"</HEAD>\n" + 
		"<BODY TEXT=\"#000000\" BGCOLOR=\"#FFFFFF\" LINK=\"#0000FF\" VLINK=\"#7F00FF\" ALINK=\"#FF0000\">\n" + 
		"<P><!-------TITLE------></P>\n" + 
		"<Center>	<h2>Pogo Release Note</h2>\n" + 
		"	(Generated Wed Feb 02 13:51:12 CET 2011)</Center><Br>\n" + 
		"<li><b>Pogo-7.0.8 - 02/02/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Fire DatReady event added on attribute.<Br>\n" + 
		"<li><b>Pogo-7.0.7 - 01/02/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; VC9 project generation added.<Br>\n" + 
		"<li><b>Pogo-7.0.6 - 27/01/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; The files and sub directories not scaned at workflow is now passed dynamicaly to the workflow.<Br>\n" + 
		"<li><b>Pogo-7.0.5 - 26/01/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Some files and sub directories are not scaned any more at workflow.<Br>\n" + 
		"<li><b>Pogo-7.0.4 - 04/01/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb with inherited class path for Pogo-6 convertion fixed.<Br>\n" + 
		"<li><b>Pogo-7.0.3 - 20/12/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb with DevVarLongArray and DevVarULongArray fixed.<Br>\n" + 
		"&nbsp; &nbsp; Pb with special characters in comments fixed.<Br>\n" + 
		"<li><b>Pogo-7.0.2 - 15/12/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb on command polled (by default) fixed.<Br>\n" + 
		"<li><b>Pogo-7.0.1 - 30/11/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; State/Status polling forbidden.<Br>\n" + 
		"<li><b>Pogo-7.0.0 - 24/09/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; First release for Tango distribution.<Br>\n" + 
		"</Body>\n" + 
		"</Html>\n" + 
		"";
}
