
package org.tango.pogo.pogo_gui;

/**
 *	HTML code to display Release Notes for this package.
 *	It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote
{
	public final String	str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<HTML>\n" + 
		"<HEAD>\n" + 
		"<Title> Release Note </Title>\n" + 
		"</HEAD>\n" + 
		"<BODY TEXT=\"#000000\" BGCOLOR=\"#FFFFFF\" LINK=\"#0000FF\" VLINK=\"#7F00FF\" ALINK=\"#FF0000\">\n" + 
		"<P><!-------TITLE------></P>\n" + 
		"<Center>	<h2>Pogo Release Note</h2>\n" + 
		"	(Generated Wed Jun 15 15:42:47 CEST 2011)</Center><Br>\n" + 
		"<li><b>Pogo-7.2.7 - 15/06/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Problem in property dialog (description & default value) fixed.<Br>\n" + 
		"<li><b>Pogo-7.2.6 - 19/05/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Mandatory device property management added.<Br>\n" + 
		"&nbsp; &nbsp; Change ToolTips management.<Br>\n" + 
		"<li><b>Pogo-7.2.5 - 16/05/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Litle bug in checkLinesToRemove() method fixed.<Br>\n" + 
		"&nbsp; &nbsp; Problem with omniORB library release number in vc project files fixed.<Br>\n" + 
		"<li><b>Pogo-7.2.4 - 02/05/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb in headers when class name has changed fixed.<Br>\n" + 
		"<li><b>Pogo-7.2.3 - 19/04/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Associated attribute for READ_WITH_WRITE added.<Br>\n" + 
		"&nbsp; &nbsp; Fixe a pb between Long and Long64.<Br>\n" + 
		"<li><b>Pogo-7.2.2 - 15/04/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Does not generate read_xxx() metod if xxx attribute is WRITE type.<Br>\n" + 
		"&nbsp; &nbsp; Add a filter on Tango types for commands.<Br>\n" + 
		"<li><b>Pogo-7.2.1 - 14/03/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Tools to modified keys (for compatibility with PogoDsl changes) in xmi file added.<Br>\n" + 
		"&nbsp; &nbsp; Exclude not generated files from vcX_proj dir for workflow.<Br>\n" + 
		"<li><b>Pogo-7.2.0 - 16/02/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Multi classes manager tool added.<Br>\n" + 
		"&nbsp; &nbsp; Additional files added for Makefile and vc9 projects.<Br>\n" + 
		"&nbsp; &nbsp; VC9 project templates improved.<Br>\n" + 
		"&nbsp; &nbsp; Bug in multi lines attribute description fixed.<Br>\n" + 
		"<li><b>Pogo-7.1.1 - 14/02/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Does not generate Classfactory.cpp and main.cpp if clas is abstract.<Br>\n" + 
		"&nbsp; &nbsp; Pb in commnads table fixed.<Br>\n" + 
		"<li><b>Pogo-7.1.0 - 10/02/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Class name change is now managed.<Br>\n" + 
		"&nbsp; &nbsp; If a xmi file is in current directory, it is proposed to be loaded.<Br>\n" + 
		"<li><b>Pogo-7.0.8 - 07/02/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb in command factory (args description) fixed.<Br>\n" + 
		"&nbsp; &nbsp; Fire DatReady event added on attribute.<Br>\n" + 
		"<li><b>Pogo-7.0.7 - 01/02/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; VC9 project generation added.<Br>\n" + 
		"<li><b>Pogo-7.0.6 - 27/01/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; The files and sub directories not scaned at workflow is now passed dynamicaly to the workflow.<Br>\n" + 
		"<li><b>Pogo-7.0.5 - 26/01/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Some files and sub directories are not scaned any more at workflow.<Br>\n" + 
		"<li><b>Pogo-7.0.4 - 04/01/2011:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb with inherited class path for Pogo-6 convertion fixed.<Br>\n" + 
		"<li><b>Pogo-7.0.3 - 20/12/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb with DevVarLongArray and DevVarULongArray fixed.<Br>\n" + 
		"&nbsp; &nbsp; Pb with special characters in comments fixed.<Br>\n" + 
		"<li><b>Pogo-7.0.2 - 15/12/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; Pb on command polled (by default) fixed.<Br>\n" + 
		"<li><b>Pogo-7.0.1 - 30/11/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; State/Status polling forbidden.<Br>\n" + 
		"<li><b>Pogo-7.0.0 - 24/09/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; First release for Tango distribution.<Br>\n" + 
		"</Body>\n" + 
		"</Html>\n" + 
		"";
}
