//+======================================================================
//
// Project:   Tango
//
// Description:  Release notes as java String
//
// $Author: verdier $
//
// Copyright (C) :      2004,2005,2006,2007,2008,2009,2009, 2010
//						European Synchrotron Radiation Facility
//                      BP 220, Grenoble 38043
//                      FRANCE
//
// This file is part of Tango.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
// $Revision: $
// $Date:  $
//
// $HeadURL: $
//
//-======================================================================

package org.tango.pogo.pogo_gui;

/**
 *	HTML code to display Release Notes for this package.
 *	It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote
{
	public final String	str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<HTML>\n" + 
		"<HEAD>\n" + 
		"<Title> Release Note </Title>\n" + 
		"</HEAD>\n" + 
		"<BODY TEXT=\"#000000\" BGCOLOR=\"#FFFFFF\" LINK=\"#0000FF\" VLINK=\"#7F00FF\" ALINK=\"#FF0000\">\n" + 
		"<P><!-------TITLE------></P>\n" + 
		"<Center>	<h2>Pogo Release Note</h2>\n" + 
		"	(Generated Mon Oct 18 14:46:39 CEST 2010)</Center><Br>\n" + 
		"<li><b>Pogo-7.0.0 - 24/09/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; First release for Tango distribution.<Br>\n" + 
		"<li><b>Pogo-7.0.0_rc3 - 03/09/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; Multi frame implemented.<Br>\n" + 
		"<li><b>Pogo-7.0.0_rc2 - 30/08/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; Little bugs fixed.<Br>\n" + 
		"<li><b>Pogo-7.0.0_rc1 - 28/07/2010:</b><Br>\n" + 
		"&nbsp; &nbsp; First release candidate for Pogo using oAW technology.<Br>\n" + 
		"</Body>\n" + 
		"</Html>\n" + 
		"";
}
