#!/bin/sh
#

#=========================================================
#
#             Internal functions
#
#=========================================================



#---------------------------------------------------------
#	Update ReleaseNote.java and revision number in target class
#---------------------------------------------------------
UpdateNotes() {

    echo "Updating ReleaseNote.java and revision number in target class....."
    sleep 2

    POGO=../org.tango.pogo.pogo_gui/target/classes
    UPDATE_CLASS=org.tango.pogo.pogo_gui.tools.UpdateRelease
    TARGET_CLASS=PogoConst
    SRC_HOME=../org.tango.pogo.pogo_gui/src/org/tango/pogo/pogo_gui
    
     
    java  -cp $POGO    $UPDATE_CLASS \
		    -file      $SRC_HOME/$TARGET_CLASS.java \
		    -release   ./pom.xml
            
}



#---------------------------------------------------------
#	Release Pogo using maven
#
#   Two prompts:
#      - First  without -SNAPSHOT  (R -1)  !!!
#      - Second with    -SNAPSHOT
#---------------------------------------------------------
ReleasePogo() {
    
    UpdateNotes()

    echo "Release Pogo using maven....."
    sleep 2
    
    # Tag directory
    cd ..
    git tag Pogo-Release-$VERSION
    
    # Clone in release dir and deploy after set version number without SNAPSHOT
    git clone . release
    cd release/fr.esrf.tango.pogo.parent && mvn release:update-versions
    mvn deploy
    
    # Manage version number with SNAPSHOT in pom files
    cd ../../fr.esrf.tango.pogo.parent && mvn release:update-versions
    cd .. && git add */pom.xml && git commit -m "increment version" && git push && git push --tags
    
    #ready to install
    cd release/org.tango.pogo.pogo_gui/target
    ls -l
    echo ""
    echo "*** You can install Pogo jar file from"
    pwd
    echo "And remove release dir"
}



#=====================================
#
#            Main part
#
#=====================================
case "$1" in

 #	----------------------------------------------
   notes)
        UpdateNotes
	;;
    

#	----------------------------------------------
	release)
		ReleasePogo
	;;

    *)
#	----------------------------------------------
#	Default case  --> Display syntax
#	----------------------------------------------
    echo "Usage: $0 { release }"
    exit 0
esac

