#!/bin/sh

#---------------------------------------
#	Set Directories
#---------------------------------------
TANGO_HOME=/segfs/tango
BACKUP_HOME=$TANGO_HOME/backup
LOG_DIR=$BACKUP_HOME/log
TEMPLATES_HOME=$TANGO_HOME/tools/pogo/templates

DOC_TARGET=$TANGO_HOME/doc/www/tango/tango_doc
CLASSES_DIR=ds_doc
CLASSES_DIR_SAV=ds_doc.bck


#---------------------------------------
#	Set Properties
#---------------------------------------
#MAIL_LIST=verdier@esrf.fr
MAIL_LIST=tango@esrf.fr

#---------------------------------------
#	Set CLASSPATH
#---------------------------------------
CLASSPATH=$TANGO_HOME/tools/bin:$TANGO_HOME/release/java/lib/TangORB.jar
export CLASSPATH

#---------------------------------------
#	Add path for java, tango2www and svn
#---------------------------------------
PATH=$PATH:$TANGO_HOME/jdk/Linux/jdk1.6.0/bin:$TANGO_HOME/bin
PATH=$PATH:/opt/CollabNet_Subversion/bin
export PATH

#---------------------------------------
#	Go to temporary dir to generate
#---------------------------------------
TMP_DIR=$TANGO_HOME/tmp/class2www
cd $TMP_DIR


#---------------------------------------
#	And start java classes
#---------------------------------------
java -DTEMPL_HOME=$TEMPLATES_HOME  \
	-D_BACKUP_HOME_=$BACKUP_HOME   \
	-D_MAIL_LIST_=$MAIL_LIST       \
	-D_DOC_TARGET_=$DOC_TARGET     \
	-D_CLASSES_DIR_=$CLASSES_DIR   \
	pogo.class2www.Class2www       \
		1>$LOG_DIR/class2www.log   \
		2>$LOG_DIR/class2www.err


#---------------------------------------
#	Save old doc
#---------------------------------------
rm -Rf $DOC_TARGET/$CLASSES_DIR_SAV
mv $DOC_TARGET/$CLASSES_DIR   $DOC_TARGET/$CLASSES_DIR_SAV
mv 	$CLASSES_DIR  $DOC_TARGET

#---------------------------------------
#	Move result to WWW
#---------------------------------------
/segfs/tango/bin/tango2www	ds_doc


#---------------------------------------
#	And remove old files
#---------------------------------------
rm -Rf $TMP_DIR/*
