/*
* generated by Xtext
*/
package fr.esrf.tango.pogo.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import fr.esrf.tango.pogo.services.PogoDslGrammarAccess;

public class PogoDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private PogoDslGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		fr.esrf.tango.pogo.parser.antlr.internal.InternalPogoDslLexer lexer = new fr.esrf.tango.pogo.parser.antlr.internal.InternalPogoDslLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		fr.esrf.tango.pogo.parser.antlr.internal.InternalPogoDslParser parser = new fr.esrf.tango.pogo.parser.antlr.internal.InternalPogoDslParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PogoSystem";
	}
	
	public PogoDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PogoDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
