/*
 * generated by Xtext
 */
package fr.esrf.tango.pogo.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.esrf.tango.pogo.ui.internal.PogoDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PogoDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PogoDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PogoDslActivator.getInstance().getInjector(PogoDslActivator.FR_ESRF_TANGO_POGO_POGODSL);
	}
	
}
