/*
 * generated by Xtext
 */
package fr.esrf.tango.pogo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PogoDslUiModule extends fr.esrf.tango.pogo.ui.AbstractPogoDslUiModule {
	public PogoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
