
package org.tango.pogo.pogo_gui;

/**
 * HTML code to display Release Notes for this package.
 * It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote {
	String str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<html>\n" + 
		"<head>\n" + 
		"<title> Release Note </title>\n" + 
		"</head>\n" + 
		"<body text=\"#000000\" bgColor=\"#FFFFFF\" link=\"#0000FF\" vLink=\"#7F00FF\" aLink=\"#FF0000\">\n" + 
		"<p><!-------TITLE------></p>\n" + 
		"<center>	<h2>Pogo Release Notes </h2>\n" + 
		"	(Generated 09-10-2017  13:02:52)</center><br>\n" + 
		"<li><b>Pogo-9.6.3 - 09/10/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a NPE in AttributeDialog.java<br>" + 
		"<li><b>Pogo-9.6.2 - 06/10/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Allow to generate ENUM attribute as spectrum and image in C++.<br>" + 
		"<li><b>Pogo-9.6.1 - 25/09/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a NPE in PyHL new class creation.<br>" + 
		"<li><b>Pogo-9.6.0 - 15/09/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; PyHL package is now memorized for next reload/generate action.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix bug in Pogo command line.<br>" + 
		"<li><b>Pogo-9.5.2 - 12/08/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; CMakeList added for widows (thanks to Sebastien)<br>" + 
		"<li><b>Pogo-9.5.1 - 10/08/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add release notes and remove unused files.<br>" + 
		"<li><b>Pogo-9.5.0 - 09/08/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Mavenized project (thanks to Igor)<br>" + 
		"<li><b>Pogo-9.4.6a - 19/04/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Cosmetic changes<br>" + 
		"<li><b>Pogo-9.4.6 - 13/01/2017:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a pdf file in doc_html on linux (if wkhtmltopdf found in path)<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug in html protected regions.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug in key word management.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add polling for State/Status in java.<br>" + 
		"<li><b>Pogo-9.4.5 - 08/12/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; A pom.xml file could be generated for java server.<br>" + 
		"&nbsp; &nbsp; &nbsp; Path must be in respect with maven structure (--/--/src/main/java)<br>" + 
		"<li><b>Pogo-9.4.4 - 06/12/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Manage mandatory properties in java templates.<br>" + 
		"<li><b>Pogo-9.4.3 - 02/12/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Remove RcsId in C++ files.<br>" + 
		"<li><b>Pogo-9.4.2 - 25/11/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; On python templates, fix Copyright on multi lines bug, some pep8 warnings, state and status when overloaded, .....<br>" + 
		"<li><b>Pogo-9.4.1 - 13/09/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve Python templates.<br>" + 
		"&nbsp; &nbsp; &nbsp; Generate CMakeLists.txt only if cmake_tango.opt found.<br>" + 
		"<li><b>Pogo-9.4.0 - 12/09/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; CMakeLists.txt file could be generated for cmake usage (linux/cpp)..<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug in Python for set_change/archive_event. The 2nd parameter was inverted.<br>" + 
		"<li><b>Pogo-9.3.0 - 04/08/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix bug in property default values in Python code.<br>" + 
		"<li><b>Pogo-9.2.9 - 12/07/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problem on resize nodes.<br>" + 
		"&nbsp; &nbsp; &nbsp; Check MonoClass/MutiClasses to open chooser.<br>" + 
		"<li><b>Pogo-9.2.8 - 28/06/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Manage state machine for dynamic attributes and commands<br>" + 
		"<li><b>Pogo-9.2.7 - 27/06/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Template management added.<br>" + 
		"<li><b>Pogo-9.2.6 - 20/05/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem with event for java dynamic attributes<br>" + 
		"<li><b>Pogo-9.2.5 - 08/04/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a clone class/device property option menu.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add an editor for class description.<br>" + 
		"<li><b>Pogo-9.2.4 - 07/03/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in pipe is_allowed method fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in pipe argument name fixed.<br>" + 
		"<li><b>Pogo-9.2.3 - 25/02/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Use of entry_points in setup.py for better compatibility.<br>" + 
		"<li><b>Pogo-9.2.2 - 04/02/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug in HTML generation with a command description empty<br>" + 
		"<li><b>Pogo-9.2.1 - 04/02/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve Python and PythonHL templates for inheritance<br>" + 
		"<li><b>Pogo-9.2.0 - 20/01/2016:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve check name for forwarded attributes.<br>" + 
		"<li><b>Pogo-9.1.12 - 02/12/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in relative path for multi classes project.<br>" + 
		"<li><b>Pogo-9.1.11 - 01/12/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Bugs in dynamic commands fixed.<br>" + 
		"<li><b>Pogo-9.1.10 - 25/11/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix bug in DevLong64 java property type<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve Python templates (path handling bug fix, protected region for run method)<br>" + 
		"<li><b>Pogo-9.1.9 - 20/11/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug protected area when rename attribute on c++.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in relative path for multi classes project.<br>" + 
		"<li><b>Pogo-9.1.8 - 19/11/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a potected region in main method for java code.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add colors on State objects.<br>" + 
		"<li><b>Pogo-9.1.7 - 02/10/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Manage relative path for inheritance and multiple classes project.<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve State machine window.<br>" + 
		"<li><b>Pogo-9.1.6 - 17/09/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve Python HL templates once more.<br>" + 
		"<li><b>Pogo-9.1.5 - 25/08/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Attribute name can start with '_'<br>" + 
		"<li><b>Pogo-9.1.4 - 14/08/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Remove DevVarBooleanArray for command (not supported)<br>" + 
		"<li><b>Pogo-9.1.3 - 04/08/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add move class on multi classes tree<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve attribute summary<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve State machine dialog size management.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add protected region at end of state machine file.<br>" + 
		"<li><b>Pogo-9.1.2 - 30/06/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Visual C++ 12 project are available for Tango-9<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve Python HL templates.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add several missing types for properties.<br>" + 
		"<li><b>Pogo-9.1.0 - 12/05/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pogo is now compiled using java 1.7<br>" + 
		"&nbsp; &nbsp; &nbsp; Double cotes supported in class description and title,<br>" + 
		"<li><b>Pogo-9.0.6 - 06/05/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Java forwarded attributes are available.<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve enum management.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug with void argin on dynamic command<br>" + 
		"<li><b>Pogo-9.0.5 - 27/04/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problem on void dynamic command fixed.<br>" + 
		"<li><b>Pogo-9.0.4 - 19/03/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; PythonHL bug fixes.<br>" + 
		"&nbsp; &nbsp; &nbsp; PythonHL test added.<br>" + 
		"<li><b>Pogo-9.0.3 - 20/01/2015:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; PythonHL bug fixes.<br>" + 
		"&nbsp; &nbsp; &nbsp; PythonHL Project directory added.<br>" + 
		"<li><b>Pogo-9.0.2 - 16/12/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in path management for multiple classes tool.<br>" + 
		"<li><b>Pogo-9.0.1 - 29/10/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; PythonHL code generation added (not tested).<br>" + 
		"<li><b>Pogo-9.0.0 - 01/10/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Tango-9 features added for C++ and java.<br>" + 
		"<li><b>Pogo-8.4.8 - 29/08/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix bugs on adding state and property type display.<br>" + 
		"<li><b>Pogo-8.4.7 - 18/06/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in linuxMakefile for additional files.<br>" + 
		"<li><b>Pogo-8.4.6 - 12/06/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add an environment variable (MANAGE_WRITE_METHOD=false) to do not modify write_xxx method.<br>" + 
		"<li><b>Pogo-8.4.5 - 23/04/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Inverse order between allocation and mandatory test in init_device().<br>" + 
		"<li><b>Pogo-8.4.4 - 07/04/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem with pushEvent in java classes.<br>" + 
		"&nbsp; &nbsp; &nbsp; Remove evironment variable _812_ (tango-8.1.2)<br>" + 
		"<li><b>Pogo-8.4.3 - 25/03/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve python dynamic attribute management.<br>" + 
		"<li><b>Pogo-8.4.2 - 19/03/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problem in python when memorized attribute does not have property.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problem on scalar attribute value.<br>" + 
		"<li><b>Pogo-8.4.0 - 26/02/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Replace TangORB.jar and ATK*.jar by a tango_ulight.jar file,<br>" + 
		"&nbsp; &nbsp; &nbsp; containing only 2 tangorb classes and 5 atk classes,<br>" + 
		"&nbsp; &nbsp; &nbsp; to decrease the org.tango.pogo.jar size (~14 Mbytes).<br>" + 
		"<li><b>Pogo-8.3.5 - 20/02/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a protected region in main method for python class<br>" + 
		"<li><b>Pogo-8.3.4 - 27/01/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a protected region for programmer methods in python class<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in changing language.<br>" + 
		"<li><b>Pogo-8.3.3 - 17/01/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug in Pogo Multiple classes.<br>" + 
		"&nbsp; &nbsp; &nbsp; Modified linux Makefile for shared libs<br>" + 
		"<li><b>Pogo-8.3.2 - 17/01/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix another problem on python class with inheritance.<br>" + 
		"<li><b>Pogo-8.3.1 - 07/01/2014:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem on python class with inheritance.<br>" + 
		"<li><b>Pogo-8.3.0 - 29/11/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; First release with packaging feature.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add javadoc throw tag for java classes.;<br>" + 
		"<li><b>Pogo-8.2.7 - 28/11/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in property default values for java classes.<br>" + 
		"<li><b>Pogo-8.2.6 - 18/11/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problem in case of exception thrown by an inherited class during startup phase.<br>" + 
		"&nbsp; &nbsp; &nbsp; Update Tango kernel link for inheritance documentation.<br>" + 
		"<li><b>Pogo-8.2.5 - 15/11/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix bug in void returning commands in python classes.<br>" + 
		"<li><b>Pogo-8.2.4 - 08/11/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve State and Status execute method code in Python classes.<br>" + 
		"&nbsp; &nbsp; &nbsp; Manage state machine for write attribute in Python classes.<br>" + 
		"<li><b>Pogo-8.2.3 - 06/11/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problem to overload State and Status commands in Python classes fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Problem in String attribute initialization for Java classes fixed<br>" + 
		"<li><b>Pogo-8.2.2 - 17/10/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a NullPointerException when class come from pogo-6 class without TangoClassID.txt file.<br>" + 
		"<li><b>Pogo-8.2.1 - 15/10/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problems in multiple classes server Makefile.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add new Tango logo.<br>" + 
		"<li><b>Pogo-8.2.0 - 14/10/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add event management for java.<br>" + 
		"<li><b>Pogo-8.1.18 - 01/10/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Change boolean attribute java method name.<br>" + 
		"<li><b>Pogo-8.1.17 - 13/09/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve properties and Attribute/Command/Property dialogs.<br>" + 
		"<li><b>Pogo-8.1.16 - 11/09/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Crash reporting management added on main.cpp.<br>" + 
		"<li><b>Pogo-8.1.15 - 02/09/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve get<Attribute> method for java class.<br>" + 
		"<li><b>Pogo-8.1.14 - 26/06/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add Tango-8.1.2 specific features.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem with state machine when attribute is modified.<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve documentation generation to be used by Class2www classes.<br>" + 
		"<li><b>Pogo-8.1.13 - 03/05/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve documentation generation to be used by Class2www cleasses.<br>" + 
		"<li><b>Pogo-8.1.12 - 02/05/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve edit source file feature.<br>" + 
		"<li><b>Pogo-8.1.11 - 26/04/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problem on READ_WITH_WRITE fixed.<br>" + 
		"<li><b>Pogo-8.1.10 - 05/04/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; State/Status polling problem fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Problem on makefile for multi classes with inheritance fixed.<br>" + 
		"<li><b>Pogo-8.1.9 - 04/03/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problem on string dynamic attribute does not compile due to a mix of const char * and char * data type<br>" + 
		"<li><b>Pogo-8.1.8 - 08/02/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Check for special char on state description.<br>" + 
		"&nbsp; &nbsp; &nbsp; Force to not memorized for spectrum/image attribute cloned from a scalar one.<br>" + 
		"<li><b>Pogo-8.1.7 - 07/02/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problem in include path in VC9 projects.<br>" + 
		"<li><b>Pogo-8.1.6 - 06/02/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem with bad char in VC9 project.<br>" + 
		"&nbsp; &nbsp; &nbsp; Change lib and include pathes in VC9 projects.<br>" + 
		"<li><b>Pogo-8.1.5 - 18/01/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problem in command using DevEncoded fixed.<br>" + 
		"<li><b>Pogo-8.1.4 - 15/01/2013:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Eclipse project added for C++ classes.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add a popup menu on main window to change language.<br>" + 
		"&nbsp; &nbsp; &nbsp; Problem in string spectrum write attribute fixed.<br>" + 
		"<li><b>Pogo-8.1.3 - 19/11/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix problem in class/device property description for python.<br>" + 
		"<li><b>Pogo-8.1.2 - 05/11/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem on inheritance.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem on remove dynamic attribute.<br>" + 
		"<li><b>Pogo-8.1.1 - 23/10/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problems in python due to generated file name fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Remove the Soleil special case.<br>" + 
		"&nbsp; &nbsp; &nbsp; Problem links to sub-directory in java fixed.<br>" + 
		"<li><b>Pogo-8.1.0 - 22/10/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; XTend replaces XPand to define templates.<br>" + 
		"&nbsp; &nbsp; &nbsp; C++ and html templates have been re written using xtend.<br>" + 
		"&nbsp; &nbsp; &nbsp; Java and Python generators are now available.<br>" + 
		"<li><b>Pogo-8.0.8 - 10/08/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add methods for future compatibility.<br>" + 
		"<li><b>Pogo-8.0.7 - 07/08/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in generate dialog for multi class project fixed.<br>" + 
		"<li><b>Pogo-8.0.7 - 27/06/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problem in allocation data member when inherited fixed.<br>" + 
		"<li><b>Pogo-8.0.6 - 21/06/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problem in write dynamic attribute fixed.<br>" + 
		"<li><b>Pogo-8.0.5 - 11/06/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; VC 10 pb with dll fixed.<br>" + 
		"<li><b>Pogo-8.0.4 - 04/06/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; zmq.lib added to vc9 project.<br>" + 
		"<li><b>Pogo-8.0.3 - 29/05/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve vc10 project.<br>" + 
		"&nbsp; &nbsp; &nbsp; Modify file filter for java classes.<br>" + 
		"<li><b>Pogo-8.0.2 - 03/05/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Bug on abstract command inherited fixed.<br>" + 
		"<li><b>Pogo-8.0.1 - 05/04/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb with inherited object when DevRestart command received fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Event criteria management added for attributes (new Tango 8 feature)<br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in inheritance for attribute_factory() fixed.<br>" + 
		"<li><b>Pogo-8.0.0 - 05/03/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve inheritance<br>" + 
		"&nbsp; &nbsp; &nbsp; Add polling on State and Status<br>" + 
		"&nbsp; &nbsp; &nbsp; Make corrections to remove warnings when compile with -Wall<br>" + 
		"&nbsp; &nbsp; &nbsp; Add ULong64 and ULong64Array.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add DevEncoded for Command.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in non double dynamic attribute.<br>" + 
		"<li><b>Pogo-7.5.0 - 30/01/2012:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Win64/VC10 project added.<br>" + 
		"&nbsp; &nbsp; &nbsp; Call for init/delete device and command factory added when class is inherited.<br>" + 
		"<li><b>Pogo-7.4.0 - 01/12/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Workflow upgrade (Eclipse-3.7, XText-2.0, XPand-1.1)<br>" + 
		"<li><b>Pogo-7.3.2 - 08/09/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Bug with DevVarLongStringArray and DevVarDoubleStringArray fixed.<br>" + 
		"<li><b>Pogo-7.3.1 - 27/07/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb with dev_state() method in case of ALARM state fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in case of main.cpp missing (convertion from pogo-6) fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Buttons for java projects added.<br>" + 
		"<li><b>Pogo-7.3.0 - 27/07/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Dynamic attributes management added.<br>" + 
		"<li><b>Pogo-7.2.7 - 15/06/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Problem in property dialog (description & default value) fixed.<br>" + 
		"<li><b>Pogo-7.2.6 - 19/05/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Mandatory device property management added.<br>" + 
		"&nbsp; &nbsp; &nbsp; Change ToolTips management.<br>" + 
		"<li><b>Pogo-7.2.5 - 16/05/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Litle bug in checkLinesToRemove() method fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Problem with omniORB library release number in vc project files fixed.<br>" + 
		"<li><b>Pogo-7.2.4 - 02/05/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in headers when class name has changed fixed.<br>" + 
		"<li><b>Pogo-7.2.3 - 19/04/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Associated attribute for READ_WITH_WRITE added.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fixe a pb between Long and Long64.<br>" + 
		"<li><b>Pogo-7.2.2 - 15/04/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Does not generate read_xxx() metod if xxx attribute is WRITE type.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add a filter on Tango types for commands.<br>" + 
		"<li><b>Pogo-7.2.1 - 14/03/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Tools to modified keys (for compatibility with PogoDsl changes) in xmi file added.<br>" + 
		"&nbsp; &nbsp; &nbsp; Exclude not generated files from vcX_proj dir for workflow.<br>" + 
		"<li><b>Pogo-7.2.0 - 16/02/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Multi classes manager tool added.<br>" + 
		"&nbsp; &nbsp; &nbsp; Additional files added for Makefile and vc9 projects.<br>" + 
		"&nbsp; &nbsp; &nbsp; VC9 project templates improved.<br>" + 
		"&nbsp; &nbsp; &nbsp; Bug in multi lines attribute description fixed.<br>" + 
		"<li><b>Pogo-7.1.1 - 14/02/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Does not generate Classfactory.cpp and main.cpp if clas is abstract.<br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in commands table fixed.<br>" + 
		"<li><b>Pogo-7.1.0 - 10/02/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Class name change is now managed.<br>" + 
		"&nbsp; &nbsp; &nbsp; If a xmi file is in current directory, it is proposed to be loaded.<br>" + 
		"<li><b>Pogo-7.0.8 - 07/02/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb in command factory (args description) fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fire DatReady event added on attribute.<br>" + 
		"<li><b>Pogo-7.0.7 - 01/02/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; VC9 project generation added.<br>" + 
		"<li><b>Pogo-7.0.6 - 27/01/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; The files and sub directories not scaned at workflow is now passed dynamicaly to the workflow.<br>" + 
		"<li><b>Pogo-7.0.5 - 26/01/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Some files and sub directories are not scaned any more at workflow.<br>" + 
		"<li><b>Pogo-7.0.4 - 04/01/2011:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb with inherited class path for Pogo-6 convertion fixed.<br>" + 
		"<li><b>Pogo-7.0.3 - 20/12/2010:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb with DevVarLongArray and DevVarULongArray fixed.<br>" + 
		"&nbsp; &nbsp; &nbsp; Pb with special characters in comments fixed.<br>" + 
		"<li><b>Pogo-7.0.2 - 15/12/2010:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Pb on command polled (by default) fixed.<br>" + 
		"<li><b>Pogo-7.0.1 - 30/11/2010:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; State/Status polling forbidden.<br>" + 
		"<li><b>Pogo-7.0.0 - 24/09/2010:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; First release for Tango distribution.<br>" + 
		"</body>\n" + 
		"</html>\n"
	;
}