/*
* generated by Xtext
*/
package fr.esrf.tango.pogo.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class PogoDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
